sudo: false
language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '10'
script:
  - 'npm run lint'
  - 'npm test'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
